<?php
$current_theme = Mage::getSingleton('core/design_package')->getPackageName();
$skin_path = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/'.$current_theme.'/default/cmsmart/onlinedesign/css';
$js_path = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS).'nb_onlinedesign/';
?>
<!DOCTYPE html>
<html lang="en" ng-app="app">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <title><?php echo 'Online Designer'; ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=1, minimum-scale=0.5, maximum-scale=1.0"/>
        <meta content="<?php echo 'Online Designer - HTML5 Designer - Online Print Solution'; ?>" name="description" />
        <meta content="<?php echo 'Online Designer'; ?>" name="keywords" />
        <meta content="Netbaseteam" name="author">
        <link type="text/css" href="<?php echo $skin_path .'/jquery-ui.min.css'; ?>" rel="stylesheet" media="all" />
        <link type="text/css" href="<?php echo $skin_path .'/font-awesome/css/font-awesome.min.css'; ?>" rel="stylesheet" media="all" />
        <link href='https://fonts.googleapis.com/css?family=Audiowide' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300italic,300' rel='stylesheet' type='text/css'>
        <link type="text/css" href="<?php echo $skin_path .'/bootstrap.min.css'; ?>" rel="stylesheet" media="all"/>
        <link type="text/css" href="<?php echo $skin_path .'/bundle.css'; ?>" rel="stylesheet" media="all"/>
        <link type="text/css" href="<?php echo $skin_path .'/owl.carousel.css'; ?>" rel="stylesheet" media="all"/>
        <link type="text/css" href="<?php echo $skin_path .'/style.min.css'; ?>" rel="stylesheet" media="all">
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->	
        <script type="text/javascript">
            var product_id = window.parent.nbds_frontend.product_id;
            var od_mainURL = window.parent.nbds_frontend.url_style;
            var orderid = '', OD_task = '';
            <?php if (isset($_GET['orderid']) && ($_GET['orderid'] != '')): ?>
                orderid = "<?php echo $_GET['orderid']; ?>";
            <?php endif; ?>
            <?php if(isset($_GET['task'])): ?>
                OD_task = "<?php echo $_GET['task']; ?>";
             <?php endif; ?>   
        </script>
    </head>
    <body ng-controller="DesignerController">
        <div class="od_loading"></div>
        <div class="container-fluid" id="designer-controller">
            <?php
            include_once('components/menu.php');
            include_once('components/design_area.php');
            include_once('components/info.php');
            ?>
        </div>
        <div id="od_modal">
            <?php
            include_once('components/modal_clipart.php');
            include_once('components/modal_upload.php');
            include_once('components/modal_qrcode.php');
            include_once('components/modal_preview.php');
            include_once('components/modal_pattern.php');
            include_once('components/modal_fonts.php');
            include_once('components/modal_crop_image.php');
            include_once('components/modal_config_art.php');
            include_once('components/modal_share.php');		
            ?>
        </div>
        <div id="od_config" ng-class="modeMobile ? 'mobile' : 'modepc'">	
            <?php
            include_once('components/config_text.php');
            include_once('components/config_clipart.php');
            include_once('components/config_image.php');
            include_once('components/config_draw.php');
            ?>
            <span class="hide-config fa fa-chevron-down e-shadow e-hover-shadow item-config" ng-show="modeMobile"></span>
            <span class="hide-tool-config fa fa-chevron-down e-shadow e-hover-shadow item-config" ng-hide="modeMobile" ng-style="{'display' : (pop.text == 'block' || pop.art == 'block' || pop.qrcode == 'block' || pop.clipArt == 'block' || pop.draw == 'block') ? 'block' : 'none'}"></span>
        </div>
        <?php
        include_once('components/popover_layer.php');
        include_once('components/tool_top.php');
        include_once('components/helpdesk.php');
        ?>
        <div class="od_processing">
            <div id="nbdesigner_preloader">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>	
            <p id="first_message"><?php echo $this->__("NBDESIGNER PROCESSING...") ?></p>
        </div>
        <script type='text/javascript' src="<?php echo $js_path.'jquery/jquery.min.js'; ?>"></script>
        <script type='text/javascript' src="<?php echo $js_path.'jquery/jquery-ui.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $js_path.'frontend/touch.js'; ?>"></script>
        <script type='text/javascript' src="<?php echo $js_path.'frontend/bootstrap.min.js'; ?>"></script>
        <script type='text/javascript' src="<?php echo $js_path.'frontend/angular.min.js'; ?>"></script>
        <script type='text/javascript' src="<?php echo $js_path.'frontend/lodash.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $js_path.'frontend/bundle.min.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $js_path.'frontend/fabric.curvedText.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $js_path.'frontend/fabric.removeColor.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $js_path.'frontend/jscolor.min.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $js_path.'frontend/_layout.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $js_path.'frontend/designer.min.js'; ?>"></script>		
    </body>
</html>