<script type="text/javascript">
    //<![CDATA[
    function check() {
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method:     'get',
            onSuccess: function(transport){
              alert('The program run complete!')
              if (transport.responseText){
                  alert('The program successfully!')
              }
            }
        });
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>
