<?php
	$id     = $this->getRequest()->getParam('id');
	$onlinedesignIds = Mage::getModel('onlinedesign/onlinedesign')->_getOnlineDesignByProduct($id);
	$data = "";
	if(sizeof($onlinedesignIds)) {
		foreach ($onlinedesignIds as $od) {
			$data = $od->getContentDesign();
			$dpi = $od->getDpi();
			break;
		}
	} else {
		$data = 'a:2:{i:0;a:9:{s:16:"orientation_name";s:7:"frame_0";s:7:"img_src";s:72:"http://onlinedesign.com/wp-content/uploads/2016/11/2015-11-13_093640.jpg";s:11:"img_src_top";s:1:"0";s:12:"img_src_left";s:1:"0";s:13:"img_src_width";s:1:"0";s:14:"img_src_height";s:1:"0";s:16:"area_design_left";s:1:"0";s:17:"area_design_width";s:3:"300";s:18:"area_design_height";s:3:"117";}i:1;a:10:{s:10:"real_width";s:2:"99";s:16:"orientation_name";s:7:"frame_1";s:7:"img_src";s:72:"http://onlinedesign.com/wp-content/uploads/2016/11/2015-11-13_093640.jpg";s:11:"img_src_top";s:1:"0";s:12:"img_src_left";s:1:"0";s:13:"img_src_width";s:1:"0";s:14:"img_src_height";s:1:"0";s:16:"area_design_left";s:1:"0";s:17:"area_design_width";s:3:"300";s:18:"area_design_height";s:3:"117";}}';
	}
	$designer_setting = unserialize($data);
	foreach ($designer_setting as $k => $v){
		 zend_debug::dump($v['orientation_name']);
	}
?>
	
<div id="nbdesigner-setting-container">
    <?php //wp_nonce_field('nbdesigner_setting_box', 'nbdesigner_setting_box_nonce'); ?>		
    <!--
	<div class="nbdesigner-left">
        <input type="hidden" value="0" name="_nbdesigner_enable"/>
        <label for="_nbdesigner_enable" class="nbdesigner-setting-box-label"><?php //echo _e('Enable Design', $this->textdomain); ?></label>
        <input type="checkbox" value="1" name="_nbdesigner_enable" id="_nbdesigner_enable" <?php //checked(get_post_meta($post_id, '_nbdesigner_enable', true)); ?> class="short" />
    </div>
	-->
    <div class="nbdesigner-right add_more" style="display: none;">
        <a class="button button-primary" onclick="NBDESIGNADMIN.addOrientation()"><?php echo $this->__('Add More'); ?></a>
    </div>
    <div class="nbdesigner-clearfix"></div>
    <div id="nbdesigner_dpi_con">
        <label for="nbdesigner_dpi" class="nbdesigner-setting-box-label"><?php echo $this->__('Dpi'); ?></label>
        <input name="_nbdesigner_dpi" id="nbdesigner_dpi" value="<?php echo $dpi;?>" type="number"  min="0" max="300" style="width: 60px;" onchange="NBDESIGNADMIN.updateSolutionImage()">&nbsp;<small>(<?php echo $this->__('Dots Per Inch'); ?>)</small>   
    </div>
    <div id="nbdesigner-boxes" class="<?php //if (!get_post_meta($post_id, '_nbdesigner_enable', true)) echo 'nbdesigner-disable'; ?>">
        <?php $count = 0;
        foreach ($designer_setting as $k => $v): ?>
            <div class="nbdesigner-box-container">
                <div class="nbdesigner-box">
                    <label class="nbdesigner-setting-box-label"><?php echo $this->__('Name:'); ?></label>
                    <div class="nbdesigner-setting-box-value">
                        <input name="_designer_setting[<?php echo $k; ?>][orientation_name]" class="short orientation_name" value="<?php echo $v['orientation_name']; ?>" type="text" required/>
                    </div>
                    <div class="nbdesigner-right">
                        <a class="button nbdesigner-collapse" onclick="NBDESIGNADMIN.collapseBox(this)"><span class="dashicons dashicons-arrow-up"></span><?php echo $this->__('Less setting'); ?></a>
                        <a class="button nbdesigner-delete delete_orientation" data-index="<?php echo $k; ?>" onclick="NBDESIGNADMIN.deleteOrientation(this)">&times;</a>
                    </div>
                </div>
                <div class="nbdesigner-box nbdesigner-box-collapse">
                    <div class="nbdesigner-image-box">
                        <div class="nbdesigner-image-inner">
                            <div class="nbdesigner-image-original">
                                <img src="<?php if ($v['img_src'] != '') {echo $v['img_src'];} //else {echo NBDESIGNER_PLUGIN_URL . 'assets/images/default.png';} ?>" 
                                     class="designer_img_src"
                                    />
                            </div>
                            <div class="nbdesigner-area-design" id="nbdesigner-area-design-<?php echo $k; ?>" style="width: <?php echo $v['area_design_width'] . 'px'; ?>; height: <?php echo $v['area_design_height'] . 'px'; ?>; left: <?php echo $v['area_design_left'] . 'px'; ?>; top: <?php echo $v['area_design_top'] . 'px'; ?>;"> </div>
                        </div>
                        <input type="hidden" class="hidden_img_src" name="_designer_setting[<?php echo $k; ?>][img_src]" value="<?php echo $v['img_src']; ?>" >
                        <input type="hidden" class="hidden_img_src_top" name="_designer_setting[<?php echo $k; ?>][img_src_top]">
                        <input type="hidden" class="hidden_img_src_left" name="_designer_setting[<?php echo $k; ?>][img_src_left]">
                        <input type="hidden" class="hidden_img_src_width" name="_designer_setting[<?php echo $k; ?>][img_src_width]">
                        <input type="hidden" class="hidden_img_src_height" name="_designer_setting[<?php echo $k; ?>][img_src_height]">
                        <div>	
                            <a class="button nbdesigner_move nbdesigner_move_left" data-index="<?php echo $k; ?>" onclick="NBDESIGNADMIN.nbdesigner_move(this, 'left')">&larr;</a>
                            <a class="button nbdesigner_move nbdesigner_move_right" data-index="<?php echo $k; ?>" onclick="NBDESIGNADMIN.nbdesigner_move(this, 'right')">&rarr;</a>
                            <a class="button nbdesigner_move nbdesigner_move_up" data-index="<?php echo $k; ?>" onclick="NBDESIGNADMIN.nbdesigner_move(this, 'up')">&uarr;</a>
                            <a class="button nbdesigner_move nbdesigner_move_down" data-index="<?php echo $k; ?>" onclick="NBDESIGNADMIN.nbdesigner_move(this, 'down')">&darr;</a>
                            <a class="button nbdesigner_move nbdesigner_move_center" data-index="<?php echo $k; ?>" onclick="NBDESIGNADMIN.nbdesigner_move(this, 'center')">&frac12;</a>
                            <a class="button nbdesigner_move nbdesigner_move_center" style="padding-left: 7px; padding-right: 7px;" data-index="<?php echo $k; ?>" onclick="NBDESIGNADMIN.nbdesigner_move(this, 'fit')"><i class="mce-ico mce-i-dfw" style="margin: 4px 0px 0px 0px !important; padding: 0 !important;"></i></a>
                            <a class="button nbdesigner-button nbdesigner-add-image" style="margin-top: 10px;" onclick="NBDESIGNADMIN.loadImage(this)" data-index="<?php echo $k; ?>"><?php echo __('Change image', $this->textdomain); ?></a>
                        </div>
                    </div>
                    <div class="nbdesigner-info-box">
                        <div class="nbdesigner-info-box-inner">
                            <label class="nbdesigner-setting-box-label"><?php echo $this->__('Real width design zone'); ?></label>
                            <div>
                                <input type="number" name="_designer_setting[<?php echo $k; ?>][real_width]" value="<?php echo $v['real_width']; ?>" class="short real_width" onchange="NBDESIGNADMIN.updateDimensionRealOutputImage(this, 'width')">&nbsp;cm <span class="real_width_hidden"><?php echo $v['real_width']; ?></span><small>~ <?php echo $this->__('Output image width'); ?>: <span class="real_width_px"><?php echo round($v['real_width'] * $dpi / 2.54, 0); ?></span> px</small>
                            </div>
                        </div>
                        <div class="nbdesigner-info-box-inner">
                            <label class="nbdesigner-setting-box-label"><?php echo $this->__('Real height design zone'); ?></label>
                            <div>
                                <input type="number"  min="1" name="_designer_setting[<?php echo $k; ?>][real_height]" value="<?php echo $v['real_height']; ?>" class="short real_height"  onchange="NBDESIGNADMIN.updateDimensionRealOutputImage(this, 'height')">&nbsp;cm <span class="real_height_hidden"><?php echo $v['real_height']; ?></span><small>~ <?php echo $this->__('Output image height'); ?>: <span class="real_height_px"><?php echo round($v['real_height'] * $dpi / 2.54, 0); ?></span> px</small>
                            </div>
                        </div>
                        <div class="nbdesigner-info-box-inner">
                            <label class="nbdesigner-setting-box-label"><?php echo $this->__('Design area margin top'); ?></label>
                            <div>
                                <input type="number"  min="1" name="_designer_setting[<?php echo $k; ?>][area_design_top]" value="<?php echo $v['area_design_top']; ?>" class="short area_design_dimension area_design_top" data-index="top" onchange="NBDESIGNADMIN.updatePositionDesignArea(this)">&nbsp;px
                            </div>
                        </div>
                        <div class="nbdesigner-info-box-inner">
                            <label class="nbdesigner-setting-box-label"><?php echo $this->__('Design area margin left'); ?></label>
                            <div>
                                <input type="number"  min="0" name="_designer_setting[<?php echo $k; ?>][area_design_left]" value="<?php echo $v['area_design_left']; ?>" class="short area_design_dimension area_design_left" data-index="left" onchange="NBDESIGNADMIN.updatePositionDesignArea(this)">&nbsp;px
                            </div>
                        </div>	
                        <div class="nbdesigner-info-box-inner">
                            <label class="nbdesigner-setting-box-label"><?php echo $this->__('Design area width'); ?></label>
                            <div>
                                <input type="number"  min="0" name="_designer_setting[<?php echo $k; ?>][area_design_width]" value="<?php echo $v['area_design_width']; ?>" class="short area_design_dimension area_design_width" data-index="width" onchange="NBDESIGNADMIN.updatePositionDesignArea(this)">&nbsp;px
                            </div>
                        </div>
                        <div class="nbdesigner-info-box-inner">
                            <label class="nbdesigner-setting-box-label"><?php echo $this->__('Design area height'); ?></label>
                            <div>
                                <input type="number"  min="0" name="_designer_setting[<?php echo $k; ?>][area_design_height]" value="<?php echo $v['area_design_height']; ?>" class="short area_design_dimension area_design_height" data-index="height" onchange="NBDESIGNADMIN.updatePositionDesignArea(this)">&nbsp;px
                            </div>
                        </div>					
                    </div>	
                </div>
            </div>
    <?php $count++;
endforeach; ?>
        <input type="hidden" value="<?php echo $count; ?>" id="nbdesigner-count-box"/>
    </div>
</div>